spring:
    cloud:
        gateway:
            routes:
            -   id: CONFIG-SERVER-EXAMPLE
                uri: lb://CONFIG-SERVER-EXAMPLE
                predicates:
                -   Path=/config/**
                # filters:
                # -   AddRequestHeader=X-Request-Foo, Bar-{segment}
            -   id: EUREKA-SERVER-EXAMPLE
                uri: lb://EUREKA-SERVER-EXAMPLE
                predicates:
                -   Path=/eureka/client**
            -   id: EUREKA-CLIENT-EXAMPLE
                uri: lb://EUREKA-CLIENT-EXAMPLE
                predicates:
                -   Path=/eureka/server**
            -   id: MONITOR-SERVER-EXAMPLE
                uri: lb://MONITOR-SERVER-EXAMPLE
                predicates:
                -   Path=/monitor/**
        config:
            discovery:
                enabled: true
                service-id: CONFIG-SERVER-EXAMPLE
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management:
    endpoint:
        beans:
            enabled: true
        health:
            show-details: always
        refresh:
            enabled: true
        web: 
            exposure:
                include: "*"