logging:
    level:
        com.netflix.discovery: 'OFF'
        org.springframework.cloud: 'DEBUG'
spring:
    cloud:
        gateway:
            routes:
            -   id: CONFIG-SERVER-EXAMPLE
                predicates:
                -   Path=/config/**
                # filters:
                # -   AddRequestHeader=X-Request-Foo, Bar-{segment}
            -   id: EUREKA-SERVER-EXAMPLE
                predicates:
                -   Path=/eurake/client**
            -   id: EUREKA-CLIENT-EXAMPLE
                predicates:
                -   Path=/eurake/server**
            -   id: MONITOR-SERVER-EXAMPLE
                predicates:
                -   Path=/monitor/**
        config:
            discovery:
                enabled: true
                service-id: CONFIG-SERVER-EXAMPLE
eureka:
    client:
        healthcheck:
            enabled: true
    instance:
        statusPageUrlPath: ${server.servlet.context-path}/info
        healthCheckUrlPath: ${server.servlet.context-path}/health
        lease-expiration-duration-in-seconds: 10
        lease-renewal-interval-in-seconds: 10
        registryFetchIntervalSeconds: 5
        service-url:
            defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG


management:
    endpoint:
        beans:
            enabled: true
        health:
            show-details: always
        refresh:
            enabled: true
        web: 
            exposure:
                include: "*"