logging:
    level:
        com.netflix.discovery: 'OFF'
        org.springframework.cloud: 'DEBUG'
spring:
    application:
        name: order
    cloud:
        config:
            discovery:
                enabled: true
            service-id: config-server-example

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        lease-expiration-duration-in-seconds: 
        lease-renewal-interval-in-seconds: 10
        health-check-url-path: ${server.context-path}health
        status-page-url-path:  ${server.context-path}info
    client:
        registryFetchIntervalSeconds: 5
        service-url:
            defaultZone: http://localhost:8761/eureka/server/eureka
        fetch-registry: false
        register-with-eureka: false
    
management:
    endpoint:
        beans:
            enabled: true
        health:
            show-details: always
        refresh:
            enabled: true
        web: 
            exposure:
                include: "*"